version: '3'
services:
  cassandra_node_template:
    image: cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=my_cluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    networks:
      - cassandra_net
networks:
  cassandra_net:
    driver: bridge