version: '3'
services:
  cassandra_node_template:
    image: cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=my_cluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
volumes:
  cassandra_data:
    driver: local
