# version: '3'
# services:
#   roach1:
#     image: cockroachdb/cockroach
#     command: start --insecure --join=roach1,roach2,roach3
#     volumes:
#       - roach1:/cockroach/cockroach-data
#     networks:
#       - roachnet
#     ports:
#       - 26257:26257
#       - 8080:8080
#   roach2:
#     image: cockroachdb/cockroach
#     command: start --insecure --join=roach1,roach2,roach3
#     volumes:
#       - roach2:/cockroach/cockroach-data
#     networks:
#       - roachnet
#     ports:
#       - 26258:26257
#       - 8081:8080
#   roach3:
#     image: cockroachdb/cockroach
#     command: start --insecure --join=roach1,roach2,roach3
#     volumes:
#       - roach3:/cockroach/cockroach-data
#     networks:
#       - roachnet
#     ports:
#       - 26259:26257
#       - 8082:8080
# networks:
#   roachnet:
# volumes:
#   roach1:
#   roach2:
#   roach3:



version: '3'
services:
  roach1:
    image: cockroachdb/cockroach
    hostname: roach1
    command: start --insecure --join=roach1:,roach2,roach3
    volumes:
      - roach1:/cockroach/cockroach-data
    networks:
      - roachnet
    ports:
      - 26257
      - 8080
  roach2:
    image: cockroachdb/cockroach
    hostname: roach2
    command: start --insecure --join=roach1,roach2,roach3
    volumes:
      - roach2:/cockroach/cockroach-data
    networks:
      - roachnet
    ports:
      - 26258
      - 8081
  roach3:
    image: cockroachdb/cockroach
    hostname: roach3
    command: start --insecure --join=roach1,roach2,roach3
    volumes:
      - roach3:/cockroach/cockroach-data
    networks:
      - roachnet
    ports:
      - 26259
      - 8082
networks:
  roachnet:
volumes:
  roach1:
  roach2:
  roach3:
